---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/15 16:59
---



---@class WindowBase : YKSupportLua.LuaWindow @窗口基类
local WindowBase = BaseClass("WindowBase", YKCore.LuaWindow)--YK.window_class()

---@param ins YKSupportLua.LuaWindow
function WindowBase:__init(ins)
    self.csuserdata = ins
    self.isNeedHideAnimation = false
    self.isNeedShowAnimation = false
end

function WindowBase:OnInit()
    Logger.Log(">>>>>WindowBase:OnInit")
end

function WindowBase:DoShowAnimation()
    self.scale = Vector2(0.3, 0.3);
    --YKCore.DOTweenFloat(self.scale.x, 1, 0.3, function(scal)
    --    if self ~= nil then
    --        self.scale = Vector2(scal, scal);
    --    end
    --end, 0, DG.Tweening.Ease.OutCirc, function()
    --    if self ~= nil and self.contentPane ~= nil then
    --        self:OnShown(self:GetData());
    --    end
    --end)
end

function WindowBase:DoHideAnimation()
    --YKCore.DOTweenFloat(self.scale.x, 0, 0.3, function(scal)
    --    if self ~= nil then
    --        self.scale = Vector2(scal, scal);
    --    end
    --end, 0, nil, function()
    --    if self ~= nil and self.contentPane ~= nil then
    --        self:HideImmediately();
    --    end
    --end)

end

function WindowBase:OnDestroy()

end

function WindowBase:OnShown(param)
end

function WindowBase:OnHide()
end

function WindowBase:OnUpdate()
end

function WindowBase:OnBtnClick(obj)

end

function WindowBase:OnColseBtn()
    self:Hide()
end

---@param ev EventData
function WindowBase:OnHandler(ev)

end

---@param btn FairyGUI.GButton
function WindowBase:OnBtnClick(btn)

end

return WindowBase
